/* Generated By:JavaCC: Do not edit this line. rowJsonParserConstants.java */
package vlang.interpreter.parsers.rowJsonParser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface rowJsonParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STEP = 7;
  /** RegularExpression Id. */
  int ENTRY = 8;
  /** RegularExpression Id. */
  int FUNCTION = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int IDENTIFIER = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int VAR = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 6>",
    "\"Step\"",
    "\"@entry\"",
    "<FUNCTION>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<STRING>",
    "<VAR>",
  };

}
